// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaAYkqglP5kY9lmAzX2xpjQU0L7m8R5Aw',
    appId: '1:296403718593:web:2fee1b7ae9b67c38dd5f40',
    messagingSenderId: '296403718593',
    projectId: 'authorization-b89d5',
    authDomain: 'authorization-b89d5.firebaseapp.com',
    storageBucket: 'authorization-b89d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVir_39mdlS0023_SG6Tw8_ifNpwpfO94',
    appId: '1:296403718593:android:f08600dd99cda728dd5f40',
    messagingSenderId: '296403718593',
    projectId: 'authorization-b89d5',
    storageBucket: 'authorization-b89d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJYOy1EI0GOvUg_uQTanJMWboEoj7W1Q',
    appId: '1:296403718593:ios:ca37e28c71a3b79fdd5f40',
    messagingSenderId: '296403718593',
    projectId: 'authorization-b89d5',
    storageBucket: 'authorization-b89d5.appspot.com',
    iosClientId:
        '296403718593-l5l425vdh2bqc6b0af2vvh9743o0c1ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.apollodemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJYOy1EI0GOvUg_uQTanJMWboEoj7W1Q',
    appId: '1:296403718593:ios:612bed82e4d9d046dd5f40',
    messagingSenderId: '296403718593',
    projectId: 'authorization-b89d5',
    storageBucket: 'authorization-b89d5.appspot.com',
    iosClientId:
        '296403718593-9lh621ur2pbseo1jkpvictoatdmpfrtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.apollodemo1.RunnerTests',
  );
}
